name: React CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run tests
        run: npm test --coverage

      - name: Build app
        run: npm run build

      - name: Deploy to Docker Hub
        run: |
          docker build -t vite-project-react .
          docker push explorernw/vite-project-react:v1.0
